{% set name = "pyserde" %}
{% set version = "0.22.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9972707cb7bbcfa1f960b8a3589cc7035d522c4c6d6675fb7ebbb0ca7668469

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >={{ python_min }}
    - typing_inspect >=0.4.0
    - typing_extensions >=4.1.0
    - casefy
    - jinja2
    - plum-dispatch >=2.3
    - beartype >=0.18.4

test:
  imports:
    - serde
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/yukinarit/pyserde
  summary: Serialization library on top of dataclasses
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
