{% set name = "pyserde" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 033d37bfba5559fd5342548076c0b86f598d7dc65f5a0896fdff690d3cfa335c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9.0,<4.0.0
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=3.9.0,<4.0.0
    - typing_inspect >=0.4.0
    - typing_extensions >=4.1.0
    - casefy
    - jinja2
    - plum-dispatch >=2,<2.3
    - beartype >=0.18.4

test:
  imports:
    - serde
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/yukinarit/pyserde
  summary: Serialization library on top of dataclasses
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
