schema_version: 1

context:
  name: pyserde
  version: "0.30.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 210d8722f40cc988f8f2e2013893c5ff24fae2062ae1f98db4dc1c750ef3dda8

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling >=1.26
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - typing_inspect >=0.4.0
    - typing_extensions >=4.1.0,<4.16.0
    - casefy
    - jinja2
    - plum-dispatch >=2.3
    - beartype >=0.18.4

tests:
  - python:
      imports:
        - serde
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Serialization library on top of dataclasses
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/yukinarit/pyserde

extra:
  recipe-maintainers:
    - thewchan
