schema_version: 1

context:
  name: pyserde
  version: "0.25.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 302a534e91d548a74722bfe1577f497ed3fd87790ac9bd4503985279622e0cd0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - poetry-core >=1.0.0
    - poetry-dynamic-versioning
  run:
    - python >=${{ python_min }}
    - typing_inspect >=0.4.0
    - typing_extensions >=4.1.0,<4.13.0
    - casefy
    - jinja2
    - plum-dispatch >=2.3
    - beartype >=0.18.4

tests:
  - python:
      imports:
        - serde
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Serialization library on top of dataclasses
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/yukinarit/pyserde

extra:
  recipe-maintainers:
    - thewchan
